#!/bin/bash

# Retrieve arguments
app=transwhat
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app admin)
arch=$(sudo yunohost app setting $app arch)
spectrum_password=$(sudo yunohost app setting $app spectrum_password)
db_pwd=$(sudo yunohost app setting $app mysqlpwd)
yowsup_version=2.4.48
final_path=/opt/yunohost/transwhat
db_user=transwhat

# Update spectrum
sudo dpkg -i --force-depends ../sources/package/libtransport-plugin2.0_1698-66f1e76-1_$arch.deb 
sudo dpkg -i --force-depends ../sources/package/libtransport2.0_1698-66f1e76-1_$arch.deb 
sudo dpkg -i --force-depends ../sources/package/spectrum2_1698-66f1e76-1_$arch.deb

# Update yowsup
tar xzf ../sources/yowsup.tar.gz
cd yowsup-$yowsup_version
sudo python setup.py install
cd ..

# Update transwhat
unzip ../sources/transwhat.zip
sudo cp -r transwhat/. $final_path/

# Install services
sed -i "s@DOMAIN@$domain@g" ../conf/systemd/spectrum.service
sudo cp -r ../conf/systemd/. /etc/systemd/system/
sudo systemctl daemon-reload

# Configure spectrum
sudo mkdir -p /etc/spectrum2/transports
sed -i "s@DB_USER@$db_user@g" ../conf/spectrum.cfg
sed -i "s@DB_PASSWORD@$db_pwd@g" ../conf/spectrum.cfg
sed -i "s@PASSWORD@$spectrum_password@g" ../conf/spectrum.cfg
sed -i "s@DOMAIN@transwhat.$domain@g" ../conf/spectrum.cfg
sed -i "s@ADMIN_NUMBER@$admin@g" ../conf/spectrum.cfg
sudo cp ../conf/spectrum.cfg /etc/spectrum2/transports/spectrum.cfg
sudo cp ../conf/spectrum_manager.cfg /etc/spectrum2/spectrum_manager.cfg
sudo cp ../conf/logging.cfg /etc/spectrum2/logging.cfg
sudo cp ../conf/backend-logging.cfg /etc/spectrum2/backend-logging.cfg

# Configure metronome
sed -i "s@DOMAIN@transwhat.$domain@g" ../conf/metronome.cfg.lua
sed -i "s@PASSWORD@$spectrum_password@g" ../conf/metronome.cfg.lua
sudo cp ../conf/metronome.cfg.lua /etc/metronome/conf.d/transwhat.$domain.cfg.lua

# Configure transwhat
sed -i "s@_DB_USER@$db_user@g" ../conf/constants.py
sed -i "s@DB_PASSWORD@$db_pwd@g" ../conf/constants.py
sudo cp ../conf/constants.py $final_path/constants.py

# Set permissions to final_path directory and log directory
sudo chown -R transwhat:transwhat $final_path
sudo chown -R transwhat:transwhat /var/log/spectrum2
sudo chmod 755 /var/log/spectrum2
sudo chmod 755 /var/log/spectrum2/transwhat.$domain
sudo chmod 755 /var/log/spectrum2/transwhat.$domain/backends

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/transwhat.conf

# Install doc directory
sudo cp -r ../sources/web_doc/. /var/www/transwhat/
sudo chown www-data:www-data -R /var/www/transwhat
sudo chmod 740 /var/www/transwhat

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo service metronome reload
sudo service spectrum restart
sudo yunohost app ssowatconf
